services:
  - type: web
    name: ai-smart-resume-evaluator
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12.8"
    healthCheckPath: /
    autoDeploy: true
